name: Main Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
  release:
    types:
      - published

jobs:
  vm-job:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        ports:
        - 3306/tcp
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: .NET Build Core
      run: dotnet build ElementSql/ElementSql.csproj -c Release /p:CI=true
    - name: .NET Build Example
      run: dotnet build ElementSql.Example/ElementSql.Example.csproj -c Release /p:CI=true
    - name: .NET Build MySqlTests
      run: dotnet build ElementSql.MySqlTests/ElementSql.MySqlTests.csproj -c Release /p:CI=true
    - name: ElementSql Unit Tests
      run: dotnet test ElementSql.Tests/ElementSql.Tests.csproj -c Release -l "console;verbosity=normal" /p:CI=true
    - name: ElementSql Integration Tests
      run: dotnet test ElementSql.MySqlTests/ElementSql.MySqlTests.csproj -c Release -l "console;verbosity=normal" /p:CI=true
      env:
        MySqlConnectionString: Server=localhost;Port=${{ job.services.mysql.ports[3306] }};Uid=root;Pwd=root;Database=test;Allow User Variables=true

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build ElementSql/ElementSql.csproj--configuration Release --no-restore

      - name: Pack the project
        run: dotnet pack ElementSql/ElementSql.csproj --configuration Release --no-build --output ./nupkg

      - name: Push the package to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
