name: Main Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
  release:
    types:
      - published
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace}}/nuget

defaults:
  run:
    shell: pwsh

jobs:
  vm-job:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        ports:
        - 3306/tcp
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: .NET Build Core
      run: dotnet build ElementSql/ElementSql.csproj -c Release /p:CI=true
    - name: .NET Build Example
      run: dotnet build ElementSql.Example/ElementSql.Example.csproj -c Release /p:CI=true
    - name: .NET Build MySqlTests
      run: dotnet build ElementSql.MySqlTests/ElementSql.MySqlTests.csproj -c Release /p:CI=true
    - name: ElementSql Unit Tests
      run: dotnet test ElementSql.Tests/ElementSql.Tests.csproj -c Release -l "console;verbosity=normal" /p:CI=true
    - name: ElementSql Integration Tests
      run: dotnet test ElementSql.MySqlTests/ElementSql.MySqlTests.csproj -c Release -l "console;verbosity=normal" /p:CI=true
      env:
        MySqlConnectionString: Server=localhost;Port=${{ job.services.mysql.ports[3306] }};Uid=root;Pwd=root;Database=test;Allow User Variables=true

  create_nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Get all history to allow automatic versioning using MinVer

    # Install the .NET SDK indicated in the global.json file
    - name: Setup .NET
      uses: actions/setup-dotnet@v4

    # Create the NuGet package in the folder from the environment variable NuGetDirectory
    - run: dotnet pack ElementSql/ElementSql.csproj --configuration Release --output ${{ env.NuGetDirectory }}

    # Publish the NuGet package as an artifact, so they can be used in the following jobs
    - uses: actions/upload-artifact@v3
      with:
        name: nuget
        if-no-files-found: error
        retention-days: 7
        path: ${{ env.NuGetDirectory }}/*.nupkg
        
  deploy:
    # Publish only when creating a GitHub Release
    # https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
    # You can update this logic if you want to manage releases differently
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: [ vm-job ]
    steps:
      # Download the NuGet package created in the previous job
      - uses: actions/download-artifact@v3
        with:
          name: nuget
          path: ${{ env.NuGetDirectory }}

      # Install the .NET SDK indicated in the global.json file
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4

      # Publish all NuGet packages to NuGet.org
      # Use --skip-duplicate to prevent errors if a package with the same version already exists.
      # If you retry a failed workflow, already published packages will be skipped without error.
      - name: Publish NuGet package
        run: |
          foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg)) {
              dotnet nuget push $file --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }
